# Generated by Django 5.0 on 2024-01-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='establecimiento',
            field=models.CharField(max_length=100),
        ),
    ]
